### ISSUE TITLE
Add catch

### ISSUE THREAD

**Issue by Tanza3D** [eclipsedteam/Dashed-V2#10]
adding Catch skin elements would be pretty easy, and would be a clever idea

**Comment by Tanza3D** [comment]
do we have catch?

**Comment by MaciekMenda** [comment]
oh yes

**Comment by Tanza3D** [comment]
no we do not! - must add catch

**Comment by Tanza3D** [comment]
me and @matthew-5pl are planning to do this later, wish us luck

**Comment by Tanza3D** [comment]
done it, committing in a minute
