### ISSUE TITLE
enhance hitcircle

### ISSUE THREAD

**Issue by Tanza3D** [eclipsedteam/Dashed-V2#3]
if anyone feels like doing this make sure not to mess up the current design all that much, i have some new design ideas though

**Comment by Tanza3D** [comment]
seems like @matthew-5pl is on the case, but i still want to have a swing at it myself

**Comment by matteofo** [comment]
gonna get on it soon.

**Comment by Tanza3D** [comment]
post your progress please~

**Comment by Tanza3D** [comment]
reverted to https://github.com/eclipsedteam/Dashed/releases/tag/v1.3 (thought it looked nicer)
